# Generated by Django 4.0.5 on 2022-06-11 19:57

import datetime
import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название объекта', max_length=100, verbose_name='Название объекта')),
                ('date', models.DateTimeField(default=datetime.datetime, verbose_name='Дата создания объекта/Дата изменения цены товара')),
                ('type', models.TextField(choices=[('Продукт', 'OFFER'), ('Категория', 'CATEGORY')], help_text='Выберите тип объекта', verbose_name='Тип объекта (Категория/Товар)')),
                ('price', models.IntegerField(blank=True, help_text='Укажите цену товара', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена товара')),
                ('parent_id', models.ForeignKey(blank=True, help_text='Укажите категорию, к которой отнсится товар', on_delete=django.db.models.deletion.CASCADE, related_name='shop_units', to='mega_market.shopunit', verbose_name='id родительской категории')),
            ],
            options={
                'verbose_name': 'Объекты маркета',
                'ordering': ('-date',),
            },
        ),
    ]
