# Generated by Django 4.0.5 on 2022-06-13 12:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания объекта/Дата изменения цены товара'),
        ),
        migrations.AlterField(
            model_name='shopunit',
            name='parent_id',
            field=models.ForeignKey(blank=True, help_text='Укажите категорию, к которой отнсится товар', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_units', to='mega_market.shopunit', verbose_name='id родительской категории'),
        ),
        migrations.AlterField(
            model_name='shopunit',
            name='price',
            field=models.IntegerField(blank=True, help_text='Укажите цену товара', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена товара'),
        ),
    ]
