# Generated by Django 4.0.5 on 2022-06-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0002_alter_shopunit_date_alter_shopunit_parent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopunit',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='childrens', to='mega_market.shopunit', verbose_name='Дочерние элементы'),
        ),
    ]
