# Generated by Django 4.0.5 on 2022-06-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0003_shopunit_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopunit',
            name='children',
        ),
    ]
