# Generated by Django 4.0.5 on 2022-06-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0005_alter_shopunit_price_alter_shopunit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopunit',
            old_name='parent_id',
            new_name='parentId',
        ),
    ]
