# Generated by Django 4.0.5 on 2022-06-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0006_rename_parent_id_shopunit_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания объекта/Дата изменения цены товара'),
        ),
    ]
